import os
#from collections import OrderedDict

EPOCH_NAME                = "epoch_info.txt"
WEIGHTS_NAME              = "weights"
NUMPY_WEIGHTS_NAME        = WEIGHTS_NAME + ".npy"
HD5_WEIGHTS_NAME          = WEIGHTS_NAME + ".hd5"
WEIGHT_HISTORY_NAME       = "weight_history"
NUMPY_WEIGHT_HISTORY_NAME = WEIGHT_HISTORY_NAME + ".npy"
EPOCH_NAME                = "epoch_info.txt"
INFO_NAME                 = "info.txt"
FILL                      = "fill"


SHARED       = "shared"
DATASET      = "dataset"
OBSERVED     = "observed"
LATENT       = "latent"
VARIABLES    = "variables"
REGULARIZERS = "regularizers"
REG          = "reg"
L1           = "l1"
L2           = "l2"
LAMBDA       = "lambda"
EPSILON      = "epsilon"

REC_HIDDEN  = "rec_hidden"
GEN_HIDDEN  = "gen_hidden"
Z_REC_DIST  = "z_rec_dist"
Z_GEN_DIST  = "z_gen_dist"
REC_Z_SPACE = "rec_z_space"
GEN_Z_SPACE = "rec_z_space"
Z_REC       = "z_rec"
Z_GEN       = "z_gen"
Z_INPUT     = "z"
Z           = "z"
N_Z         = "n_z"
PRIOR       = "prior"
A           = "a"
B           = "b"
MU          = "mu"
VAR         = "var"
NU          = "nu"
LOG_PREC_MU = "log_prec_mu"
LOG_PREC_VAR = "log_prec_var"
U_Z         = "u_z"
MODEL       = "model"
WEIGHTS     = "weights"
BIASES      = "biases"
ACTIVATION        = "activation"
ACTIVATION_INPUT  = "activation_input"
USE_DROPOUT = "use_dropout"
KEEP_RATE   = "keep_rate"
DROPOUT     = "dropout"
SHORT       = "short"
MASK        = "mask"

N_UNITS     = "n_units"
TRANSFER    = "transfer"

MIN_VARIANCE    = "min_variance"
MAX_VARIANCE    = "max_variance"

ARCHITECTURES = "architectures"
ARCHITECTURE = "architecture"
NETWORK     = "network"
LAYERS      = "layers"
DATA_LAYERS      = "data_layers"
LAYER       = "layer"
SOURCE_LAYERS = "source_layers"

TRAIN_MODE = "train_mode"
OBSERVATION_LAYER = "observation_layer"
INPUT_OBSERVATIONS = "INPUT_observations"
INPUT_WEIGHTED_OBSERVATIONS = "INPUT_weighted_observations"
INPUT_MISSING = "INPUT_missing"
INPUT_CUSTOM_WEIGHTS="INPUT_custom_weights"

INPUTS      = "inputs"
INPUT       = "input"
OUTPUT      = "output"
INPUT_SOURCES = "input_sources"
TARGET_SOURCES = "target_sources"
OBSERVATIONS = "observations"
SHAPE       = "shape"
DATA        = "data"
INFO        = "info"
VARIABLES   = "variables"
PARAMETERS  = "parameters"
NAME        = "name"
RECOGNITION = "recognition"
GENERATIVE  = "generative"
ALGORITHM   = "algorithm"
CALL_BACKS  = "call_backs"
FUNCTION    = "function"
RATE        = "rate"
DATA_LOGLIK    = "data_loglik"
REC_Z_LOGLIK   = "rec_loglik"
PRIOR_Z_LOGLIK = "prior_loglik"
INTER_Z_KL          = "inter_z_kl"
INTER_Z_KL_PENALTY  = "inter_z_kl_penalty"
INTER_Z_KL_MASK     ="inter_z_kl_mask"
N_TRAIN = "n_train"
N_TEST  = "n_test"
N_VAL   = "n_val"

VAE = "vae"
FEEDFORWARD = "feedforward"

LOGLIK_FACTOR       = "loglik_factor"
LEARNING_RATE       = "learning_rate"  
LEARNING_RATE_DECAY = "learning_rate_decay"
MIN_LEARNING_RATE   = "min_learning_rate"
OPTIMIZER           = "optimizer"
EPOCH               = "epoch"
EPOCHS              = "epochs"

BATCHER             = "batcher"
BATCH_CALLBACK      = "batch_callback"
BATCH_SIZE          = "batch_size"
BATCH_IDS           = "batch_ids"
BATCH_FEED_DICT     = "batch_feed_dict"
BATCH_FEED_IMPUTATION = "batch_feed_imputation"
TRAIN_FEED_IMPUTATION = "train_feed_imputation"

TEST_FEED_IMPUTATION = "test_feed_imputation"
TEST_FEED_DICT      = "test_feed_dict"
VAL_FEED_IMPUTATION = "val_feed_imputation"
VAL_FEED_DICT       = "val_feed_dict"
FEED_DICT           = "feed_dict"

LEARNING_DECAY      = "learning_decay" 
MODEL_VIEWER        = "model_viewer"
LATENT_SAVER        = "latent_saver"
EPOCH_VIEWER        = "epoch_viewer"

SAVE_LATENT   = "save_latent"
SAVE_MODEL   = "save_model"
BATCH_EPOCH  = "batch_epoch"
TEST_EPOCH  = "test_epoch"
TEST_FILL     = "test_fill"
MODEL_VIZ     = "model_viz"
EPOCH_VIZ     = "epoch_viz"
LATENT_VIZ    = "latent_viz"

KEEP_RATES = "keep_rates"
KEEP_RATE  = "keep_rate"

BATCH_SOURCE_LOGPDF = "Batch_SourceLogPdf"
TEST_SOURCE_LOGPDF = "Test_SourceLogPdf"
VAL_SOURCE_LOGPDF = "Val_SourceLogPdf"

TEST_FILL_LOGLIK  = "Test_LogLik"
TEST_FILL_ERROR  = "Test_Error"

VAL_FILL_LOGLIK  = "Val_LogLik"
VAL_FILL_ERROR  = "Val_Error"