
BARCODES        = "barcodes"
CLINICAL        = "CLINICAL"
METH            = "METH"
MUTATIONS       = "mutations"
RNA             = "RNA"
DNA             = "DNA"
RNA_INPUT       = "RNA_input"
RNA_TARGET      = "RNA_target"
RNA_TARGET_MASK = "RNA_target_mask"
RNA_GEN_DIST    = "RNA_gen_dist"
DNA_INPUT       = "DNA_input"
DNA_TARGET      = "DNA_target"
DNA_TARGET_MASK = "DNA_target_mask"
DNA_GEN_DIST    = "DNA_gen_dist"
METH_INPUT      = "METH_input"
METH_TARGET     = "METH_target"
METH_GEN_DIST   = "METH_gen_dist"
METH_TARGET_MASK = "METH_target_mask"
TISSUE_INPUT     = "TISSUE_input"
TISSUE_TARGET    = "TISSUE_target"
TISSUE_GEN_DIST  = "TISSUE_gen_dist"
FAIR             = "FAIR"

CHANNEL      = "channel"
VARIANT      = "variant"
DISEASE      = "disease"
TISSUE       = "TISSUE"

T_REC_DIST  = "t_rec_dist"
T_GEN_DIST  = "t_gen_dist"

ALL              = "all"
FULL             = "full"
N_TRAIN_FULL     = "n_train_full"
N_TRAIN_NON_FULL = "n_train_non_full"
N_TRAIN_ALL      = "n_train_all"